# Generated by Django 3.0.5 on 2020-04-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short',
            new_name='code',
        ),
    ]
