# Generated by Django 3.0.5 on 2020-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_auto_20200416_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(default='', editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='long',
            field=models.CharField(default='', editable=False, max_length=100, null=True, unique=True),
        ),
    ]
