# Generated by Django 3.0.5 on 2020-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_auto_20200409_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.CharField(max_length=6),
        ),
    ]
