# Generated by Django 3.0.4 on 2020-04-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_to_shorten',
            name='content',
        ),
    ]
