# Generated by Django 3.0.4 on 2020-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_remove_item_to_shorten_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_to_shorten',
            name='big_url',
            field=models.URLField(default=None),
        ),
    ]
