# Generated by Django 3.0.5 on 2020-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200413_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='posts/'),
        ),
    ]
